### ISSUE TITLE
Blank todos and same todos

### ISSUE THREAD

**Issue by serhhan** [yashsehgal/todo_application#2]
It's allowing us to add blank todos and the same todos that already on the list.

**Comment by yashsehgal** [comment]
Yeah you're right! Thanks for raising this issue.
Also, would you like to work on this feature?

**Comment by rushiv7** [comment]
Hey @yashsehgal I would like to work on this.

**Comment by yashsehgal** [comment]
Alright @rushiv7 , I am assigning this issue to you. Waiting for something great.

Also, If you face any problem then feel free to ask. 😄
