### ISSUE TITLE
Add favicon in website 

### ISSUE THREAD

**Issue by amjadnoor** [yashsehgal/todo_application#3]
Using favicon is one type of branding. So, assign it to me.
<kbd>I want to use this image for favicon. What do you think about this image.</kbd>
![favicon](https://user-images.githubusercontent.com/56997478/116238768-6dd08780-a77f-11eb-9072-1213a5e65f1e.png)
<kbd>If you want another favicon then give it to me here I will download it and add it.</kbd>
Thanks 😊

**Comment by yashsehgal** [comment]
Hey, @AmjadNoor Thanks for raising this issue. 
Yup, I was also thinking to add a favicon. You can get started with this feature request and I would love to assign this to you 😄 

But before getting started, I want you to design a logo. This one is nice but too generic.

**Comment by amjadnoor** [comment]
> Hey, @AmjadNoor Thanks for raising this issue.
> Yup, I was also thinking to add a favicon. You can get started with this feature request and I would love to assign this to you 😄
> 
> But before getting started, I want you to design a logo. This one is nice but too generic.

Ok

**Comment by amjadnoor** [comment]
Give me logo for favicon please...

**Comment by yashsehgal** [comment]
@AmjadNoor Sure, I will share one here

**Comment by yashsehgal** [comment]
![TODO_Logo](https://user-images.githubusercontent.com/62352288/116501085-949cd400-a8cd-11eb-9508-7c15340cec6a.png)

You can download and use this logo as the favicon. Also, do you want to do some changes to this?

**Comment by AmjadNoor** [comment]
@yashsehgal Close this issue.
